feat: add documentation
edenlabllc/kodjin.cli pull request #1
Opened 2024-11-07 17:56 UTC by svetavedmed

2025-02-25 11:22 UTC, ypmacc requested changes

2025-02-25 11:22 UTC, ypmacc commented on README.md
> +The `Kodjin cli` is a command-line tool designed to simplify the process of downloading, installing, and managing FHIR Implementation Guides (IGs) for FHIR servers. The tool automates fetching IGі an
IGi -> IG

2025-02-25 11:22 UTC, ypmacc commented on docs/command-download.md
> +The option `--preprocess` allow you to perform all actions that is done by the install command. This could be usefull if you want to wark with conformance resources locally.
wark - > work

2025-02-25 11:22 UTC, ypmacc commented on docs/command-generate-completions.md
> +Use the next command to generate the file in fish
fish -> powershell

2025-02-25 11:22 UTC, ypmacc commented on docs/command-help.md
> +Usage: kodjin-cli [OPTIONS] <COMMAND>
It's not clear. Shouldn't it be --help command?

2025-02-25 11:22 UTC, ypmacc commented on docs/global-options.md
> +  Usage: kodjin-cli [OPTIONS] <COMMAND>
I'm not sure why full commands are listed in --help section.

2025-09-28 06:24 UTC, ilya-zlobintsev requested changes
Also need to fix conflict and update README.md

2025-09-28 06:24 UTC, ilya-zlobintsev commented on docs/authentication.md
> +```
This doesn't make much sense in a shell context, both passing the secret directly and setting an env var will be stored in shell history

2025-09-28 06:24 UTC, ilya-zlobintsev commented on docs/command-generate-completions.md
> +Remember to open a new shell to test the functionality.
I don't think we need to list this manually per-shell, `--install` already does the same thing

2025-12-12 08:00 UTC, ilya-zlobintsev requested changes

2025-12-12 08:00 UTC, ilya-zlobintsev commented on docs/about-kodjin-cli.md
> +description: The Kodjin CLI is a command-line tool designed to simplify the process of downloading, installing, and managing FHIR Implementation Guides (IGs) for FHIR servers.
`The Kodjin CLI` -> `Kodjin CLI`
same in other places

2025-12-12 08:00 UTC, ilya-zlobintsev commented on docs/authentication.md
> +```
This is outdated now that there is a builtin auth parameter

2025-12-12 08:00 UTC, ilya-zlobintsev commented on docs/CODE_OF_CONDUCT.md
> +# Contributor Covenant Code of Conduct
Where is this taken from, do we need a code of conduct right away?

2025-12-12 09:56 UTC, svetavedmed commented on docs/CODE_OF_CONDUCT.md
> +# Contributor Covenant Code of Conduct
it is taken from rmk

2025-12-15 21:09 UTC, ilya-zlobintsev approved these changes

2025-12-16 06:40 UTC, merged